DROP DATABASE IF EXISTS simpson_quotes;
CREATE DATABASE simpson_quotes;
USE simpson_quotes;

CREATE TABLE characters (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE quotes (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    character_id INT NOT NULL,
    quote VARCHAR(255) NOT NULL,
    FOREIGN KEY (character_id) REFERENCES characters(id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO characters (id, `name`)
VALUES (1, 'Homero Simpson'),
       (2, 'Marge Simpson'),
       (3, 'Bart Simpson'),
       (4, 'Lisa Simpson'),
       (5, 'Maggie Simpson'),
       (6, 'Abraham Simpson'),
       (7, 'Patty Bouvier'),
       (8, 'Seymour Skinner'),
       (9, 'Nelson Muntz'),
       (10, 'Troy McClure'),
       (11, 'Martin Prince'),
       (12, 'Bill Gates'),
       (13, 'Kent Brockman'),
       (14, 'Los Ramones'),
       (15, 'Lanz Murdock'),
       (16, 'Krusty el payaso'),
       (17, 'Sherri y Terri'),
       (18, 'Willie el escocés'),
       (19, 'Rafa Górgory'),
       (20, 'Otto Mann'),
       (21, 'Lenny Leonard'),
       (22, 'Ned Flanders'),
       (23, 'Helen Alegría'),
       (24, 'Hombre Radioactivo'),
       (25, 'Montgomery Burns'),
       (26, 'Barney Gomez'),
       (27, 'Milhouse Van Houten'),
       (28, 'Alcalde Diamante'),
       (29, 'Piloto'),
       (30, 'Policia');

INSERT INTO quotes (id, character_id, quote)
VALUES (1, 1, 'No estaba dormido... estaba EBRIO!!!'),
       (2, 7, 'Ahí va mi último rastro de deseo heterosexual'),
       (3, 1, 'Los santos fueron una bazofia anoche, todo es bazofia. He visto muchas bazofias, pero estos son la mayor bazofia entre las bazofias!'),
       (4, 8, 'Fue un accidente de pancha'),
       (5, 6, 'Mi Homero no es comunista podra ser mentiroso, puerco, idiota, comunista pero nunca una estrella de porno'),
       (6, 9, 'Destruiste el auto de Hitler, que te ha hecho él a ti?'),
       (7, 1, 'Ya sabes como escribe la gente: querido fulanito o fulanita, como has estado. Blah, blah, blah. Con todo cariño: cualquier payaso'),
       (8, 1, 'Sin la presencia de un hombre en la casa te puedes volver afeminado en un segundo...ay esta grasa que no se quita'),
       (9, 11, 'Esta es la historia de Nelson, y su gran amigo Martin..juntos hicieron hazañas..grandes grandes..'),
       (10, 10, 'Nunca lo dudes jimmy, si una vaca tuviera la oportunidad te comeria a ti y a los seres que tu mas quieres'),
       (11, 6, 'Homero, eres tonto como una piedra y feo como una blasfemia, si algun extraño ofrece a llevarte, te subes'),
       (12, 12, 'Comprenlo Muchachos, No Me Hice Rico Firmando Cheques'),
       (13, 5, 'El universo es muy confuso realmente'),
       (14, 13, 'Lo dije antes y lo digo de nuevo: la democracia simplemente no funciona'),
       (15, 14, '¡Queremos decir que esta fiesta es un bodrio! !Sí, vayan al demonio Springfield!'),
       (16, 15, 'Por si no sobrevivo, quiero despedirme con mi lema: que viva el peligro y el sudor frío'),
       (17, 17, 'A las siete de la noche se van a enfrentar, Bart contra Lisa ¿quién va a ganar? Su padre es gordo y su madre, flaca, su abuelo apesta a sudor de vaca'),
       (18, 1, 'Sé que nunca creí en ti, pero si en verdad estás en el cielo....Ayúdame Superman!!!'),
       (19, 16, 'Asi es el espectaculo muchacho, un dia eres la estrella maxima, y al otro eres un don-nadie trabajando en una fabrica de cajas'),
       (20, 4, 'Soy la reina de los lagartos!!!!'),
       (21, 18, 'Bonjourrrrrrrrrrrr... pedazo de zoquetes!'),
       (22, 19, '¿Yo reprobar aspañol? ¡Ser amposible!'),
       (23, 20, 'Me llamo Otto y me encanta todo lo que marea.'),
       (24, 3, 'Adiós Nicanor!!'),
       (25, 3, 'Has cambiado viejo, antes eras chévere!'),
       (26, 3, 'Yo no fui!'),
       (27, 1, 'A la grande le puse Cuca..'),
       (28, 1, 'Voy a apretar el botón del asensual... digo, ascensor'),
       (29, 1, 'Piensa en algo feo, piensa en algo feo!'),
       (30, 1, 'El matrimonio es como una naranja'),
       (31, 1, 'Dónde está mi hamburguesa?! Dónde está mi hamburguesa?!'),
       (32, 1, 'Creo que le habla a usted...'),
       (33, 21, 'Adiós plan dental!'),
       (34, 18, 'Malditos escoceses, arruinaron a Escocia!'),
       (35, 1, 'Ya me conoces Marge, me gusta la música fuerte, la cerveza fría y los homsexuales locas, locas, siii..'),
       (36, 1, 'Y si era tan listo por que se murió?'),
       (37, 1, 'Esa es una maldita mentira y tu lo sabes'),
       (38, 2, 'En un momento así solo se puede reir'),
       (39, 3, 'Lisa lloró, luego yo lloré y Maggie rió, todo fué una confusión'),
       (40, 9, 'A mi se me hace que eres marica'),
       (41, 9, 'Es que pensé en una chamacona'),
       (42, 22, 'Si es amarillo seguro es juguillo, si es turbio y picosón es sidra muchachón'),
       (43, 23, 'Alguien quiere pensar en los niños!!'),
       (44, 24, 'A darle átomos!'),
       (45, 19, 'Ya me gustan los niños'),
       (46, 25, 'Ahora vé y pégale a esa galletita.. Looco!!'),
       (47, 1, 'Que no has oido el refrán.. agua pasa por mi casa, cate de mi corazón'),
       (48, 1, 'Este es el mejor beso que he recibido el día de hoy. O no?'),
       (49, 26, 'A mi lo que me preocupa es el suministro de cerveza.. despues de esta caja y la otra ya solo queda una caja.'),
       (50, 26, 'Solo digo que al morir habrá un cielo para los chinos, uno para los franceses.. y todos seremos felices!!'),
       (51, 1, 'Estúpido y Sensual Flanders'),
       (52, 2, 'Para encontrar a Flanders solo tengo que pensar como Flanders... "Soy un santurrón idiota y me pongo el mismo sueter todos los días"... El río Springfield!!'),
       (53, 27, 'Te acuerdas de Alf? volvió.. en forma de fichas..'),
       (54, 27, 'Ay mis anteooojos!!'),
       (55, 22, 'Como si no llevara nada puesto.. Nada puesto!!'),
       (56, 3, 'Es como decimos en latin lisa eres una "sonsus soquetus"'),
       (57, 3, '.. y entonces le dije a Mariana.. chata..'),
       (58, 28, 'En cuanto supe de el problema tome el primer vuelo a Spring.. fal .. fel  fil!'),
       (59, 6, 'En mis tiempos los hombres de metal usaban cabeza de cono y mostraban respeto'),
       (60, 1, 'No... ese no era el inspector de billeteras.. mmhhh..'),
       (61, 29, 'Bienvenidos a la tierra de Tomy y Daly, el parque de diversiones del futuro donde nada puede malir sal.'),
       (62, 30, 'Usted no aprende, verdad?');

\! echo "Seed complete! :D"
